name: build

on:
  push:
    tags:
      - 'v*.*.*' # se ejecuta al pushear un tag tipo v0.1.0

permissions:
  contents: write  # necesario para subir assets a la release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install esbuild
        run: npm i -g esbuild

      - name: Build bundles
        run: |
          mkdir -p dist
          # 1) runtime (scrapers + hosts [dot])
          esbuild esm/dotfa-runtime.js \
            --bundle --minify --format=esm --target=es2019 \
            --legal-comments=none \
            --outfile=dist/runtime.min.js

          # 2) componentes UI genéricos (x-*)
          esbuild esm/components/index.js \
            --bundle --minify --format=esm --target=es2019 \
            --legal-comments=none \
            --outfile=dist/components.min.js

          # 3) componentes de formularios
          esbuild esm/components/forms/index.js \
            --bundle --minify --format=esm --target=es2019 \
            --legal-comments=none \
            --outfile=dist/forms.min.js

      - name: Upload to release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/runtime.min.js
            dist/components.min.js
            dist/forms.min.js
